# Programming Lab
# Assignment 3

## Deepak Khatri-202311042
## oct 4

## Que-1: Implement a custom exception named "CustomOutOfRangeError." Write a Python program that asks the user to enter an integer within a specified range (e.g., 10 to 50). If the input is outside this range, raise the "CustomOutOfRangeError" with a meaningful error message. Handle this exception and ask the user for input again until a valid input is provided.

In [2]:
class CustomOutOfRange(Exception):
    def __init__(self, message = "Input is out of range"):
        self.message = message
        super().__init__(self.message)
def get_valid_num():
    try:
        num = int(input("Enter the num between 10 to 50 range: "))
        if 10<=num<=50:
            print(num)
        else:
            raise CustomOutOfRange()
    except CustomOutOfRange as e:
        print(e)
        return get_valid_num()
    except ValueError:
        print("Invalid input, please enter it again")
        return get_valid_num()
    
try:
    valid_input = get_valid_num()
    print("you entered valid num",valid_input)
except KeyboardInterrupt:
    print("\n programe terminated")


Input is out of range
Input is out of range
36
you entered valid num None


## Que-2: Write a Python program that reads data from a CSV file. Implement exception handling to manage potential errors such as file not found, invalid data format, or missing columns. Create a custom exception "CSVDataError" to handle issues related to data format. Display appropriate error messages for different exceptions.

In [21]:
from tabulate import tabulate

class CSVDataError(Exception):
    def __init__(self, message="CSV data error"):
        self.message = message
        super().__init__(self.message)

def read_csv_file(file_path):
    try:
        with open(file_path, 'r') as file:
            header = file.readline().strip().split(',')
            data = []
            for line in file:
                values = line.strip().split(',')
                if len(values) != len(header):
                    raise CSVDataError("Number of columns in the CSV data is inconsistent.")
                data.append(values)
            return header, data
    except FileNotFoundError:
        raise FileNotFoundError(f"File '{file_path}' not found.")
    except CSVDataError as e:
        raise e
    except Exception as e:
        raise Exception(f"An unexpected error occurred: {e}")

In [22]:
file_path = 'temfp.csv'
try:
    header, data = read_csv_file(file_path)
    table = tabulate(data, header, tablefmt="grid")
    print(table)
except FileNotFoundError as e:
    print(e)
except CSVDataError as e:
    print(f"CSV Data Error: {e}")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

File 'temfp.csv' not found.


In [25]:
file_path = 'temp.csv'
try:
    header, data = read_csv_file(file_path)
    table = tabulate(data, header, tablefmt="grid")
    print(table)
except FileNotFoundError as e:
    print(e)
except CSVDataError as e:
    print(f"CSV Data Error: {e}")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

+--------+--------+--------+
| col1   | col2   | col3   |
+========+========+========+
| d1     | d2     | d3     |
+--------+--------+--------+
| a1     | a2     | a3     |
+--------+--------+--------+


In [27]:
file_path = 'temp2.csv'
try:
    header, data = read_csv_file(file_path)
    table = tabulate(data, header, tablefmt="grid")
    print(table)
except FileNotFoundError as e:
    print(e)
except CSVDataError as e:
    print(f"CSV Data Error: {e}")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

CSV Data Error: Number of columns in the CSV data is inconsistent.


## Que-3: Create a Python module that defines a function to calculate the nth Fibonacci number. Import this module into another script and use the function to calculate the Fibonacci sequence for the first 15 numbers. Display the results.

In [ ]:
# def fib(n):
#     a,b = 0,1
#     while a<n:
#         print(a,end="")
#         a,b = b,a+b
#     print()

In [1]:
import fibo
print(fibo.fib(15))

011235813
None


## Que-4: Develop a Python module that provides functionalities for matrix operations, including addition, subtraction, and multiplication using NumPy. Use this module to perform matrix multiplication on two randomly generated matrices.

In [ ]:
# import numpy as np
# def matrix_add(matrix1,matrix2):
#     try:
#         result  = np.add(matrix1,matrix2)
#         return result
#     except ValueError:
#         return "Matrix dimension must be same"
# def matrix_subtract(matrix1,matrix2):
#     try:
#         result  = np.subtract(matrix1,matrix2)
#         return result
#     except ValueError:
#         return "Matrix dimension must be same"
# def matrix_mul(matrix1,matrix2):
#     try:
#         result  = np.dot(matrix1,matrix2)
#         return result
#     except ValueError:
#         return "Matrix are not suitable for multiplication "

In [33]:

import numpy as np
import matrix
matrix_a = np.random.randint(1, 10, size=(4, 4))
matrix_b = np.random.randint(1, 10, size=(4, 4))
print("addition of matrix\n",matrix.matrix_add(matrix_a,matrix_b))
print("subtraction of matrix\n",matrix.matrix_subtract(matrix_a,matrix_b))
print("multipliation of matrix\n",matrix.matrix_mul(matrix_a,matrix_b))


addition of matrix
 [[14  9 11  9]
 [ 6 10 16 12]
 [10  8 11 11]
 [ 9  4 10  7]]
subtraction of matrix
 [[ 0 -3  1 -1]
 [-4  8  2  6]
 [ 2  2 -7  7]
 [ 3  2  6 -5]]
multipliation of matrix
 [[100  67 118  80]
 [115  51 167 104]
 [102  56 101 103]
 [ 92  64 125  61]]


## Que-5: Write a Python program that generates a 10x10 numpy array with random integers between 1 and 100. Find and display the indices of the top 5 maximum values in the array.

In [11]:
matrix_x = np.random.randint(1,100,size=(10,10))
matrix_x

array([[94, 69, 14,  6, 92, 24, 70, 97, 82, 63],
       [47, 79, 47, 66, 18, 41, 95, 61, 61, 11],
       [36,  8, 23, 62, 76, 64, 28, 40, 61, 72],
       [82, 87, 44,  5, 22, 10, 38, 52, 66, 55],
       [ 8, 26, 14, 14, 36, 51, 89, 99, 21, 50],
       [96, 48, 38, 34, 70, 78, 58, 48, 46, 47],
       [73, 73, 33, 66, 99, 78, 87, 46, 23, 45],
       [67,  3, 77, 89, 74, 82, 87,  5, 84, 46],
       [85, 79, 51, 54, 31,  7, 82,  7, 94, 40],
       [14, 51, 70, 41, 29, 76, 41, 41, 11, 34]])

In [32]:

top_indices = np.unravel_index(np.argsort(matrix_x, axis=None)[-5:], matrix_x.shape)

print("\nIndices of the Top 5 Maximum Values:\n")
for i in range(4,-1,-1):
    print(f"Top {5-i} value: {matrix_x[top_indices[0][i], top_indices[1][i]]} at index {top_indices[0][i]}, {top_indices[1][i]}")


Indices of the Top 5 Maximum Values:

Top 1 value: 99 at index 6, 4
Top 2 value: 99 at index 4, 7
Top 3 value: 97 at index 0, 7
Top 4 value: 96 at index 5, 0
Top 5 value: 95 at index 1, 6
