# Programming Lab
# Assignment 3

## Deepak Khatri-202311042
## oct 4

## Que-1: Implement a custom exception named "CustomOutOfRangeError." Write a Python program that asks the user to enter an integer within a specified range (e.g., 10 to 50). If the input is outside this range, raise the "CustomOutOfRangeError" with a meaningful error message. Handle this exception and ask the user for input again until a valid input is provided.

In [2]:
class CustomOutOfRange(Exception):
    def __init__(self, message = "Input is out of range"):
        self.message = message
        super().__init__(self.message)
def get_valid_num():
    try:
        num = int(input("Enter the num between 10 to 50 range: "))
        if 10<=num<=50:
            print(num)
        else:
            raise CustomOutOfRange()
    except CustomOutOfRange as e:
        print(e)
        return get_valid_num()
    except ValueError:
        print("Invalid input, please enter it again")
        return get_valid_num()
    
try:
    valid_input = get_valid_num()
    print("you entered valid num",valid_input)
except KeyboardInterrupt:
    print("\n programe terminated")


Input is out of range
Input is out of range
36
you entered valid num None


## Que-2: Write a Python program that reads data from a CSV file. Implement exception handling to manage potential errors such as file not found, invalid data format, or missing columns. Create a custom exception "CSVDataError" to handle issues related to data format. Display appropriate error messages for different exceptions.

## Que-3: Create a Python module that defines a function to calculate the nth Fibonacci number. Import this module into another script and use the function to calculate the Fibonacci sequence for the first 15 numbers. Display the results.

In [1]:
import fibo
print(fibo.fib(15))

011235813
None


## Que-4: Develop a Python module that provides functionalities for matrix operations, including addition, subtraction, and multiplication using NumPy. Use this module to perform matrix multiplication on two randomly generated matrices.

In [9]:
##
import numpy as np
import matrix
matrix_a = np.random.randint(1, 10, size=(4, 4))
matrix_b = np.random.randint(1, 10, size=(4, 4))
print("addition of matrix\n",matrix.matrix_add(matrix_a,matrix_b))
print("subtraction of matrix\n",matrix.matrix_subtract(matrix_a,matrix_b))
print("multipliation of matrix\n",matrix.matrix_mul(matrix_a,matrix_b))


addition of matrix
 [[16 13  6  8]
 [ 7 10  9 16]
 [ 4  7  4 13]
 [ 2  7  9  7]]
subtraction of matrix
 [[ 2  1  0 -6]
 [-3  6  1 -2]
 [ 2 -1 -2  1]
 [ 0  1  3  1]]
multipliation of matrix
 [[102  83  67 147]
 [ 66  69  74 137]
 [ 44  49  45  75]
 [ 37  50  49  91]]


## Que-5: Write a Python program that generates a 10x10 numpy array with random integers between 1 and 100. Find and display the indices of the top 5 maximum values in the array.

In [11]:
matrix_x = np.random.randint(1,100,size=(10,10))
matrix_x

array([[94, 69, 14,  6, 92, 24, 70, 97, 82, 63],
       [47, 79, 47, 66, 18, 41, 95, 61, 61, 11],
       [36,  8, 23, 62, 76, 64, 28, 40, 61, 72],
       [82, 87, 44,  5, 22, 10, 38, 52, 66, 55],
       [ 8, 26, 14, 14, 36, 51, 89, 99, 21, 50],
       [96, 48, 38, 34, 70, 78, 58, 48, 46, 47],
       [73, 73, 33, 66, 99, 78, 87, 46, 23, 45],
       [67,  3, 77, 89, 74, 82, 87,  5, 84, 46],
       [85, 79, 51, 54, 31,  7, 82,  7, 94, 40],
       [14, 51, 70, 41, 29, 76, 41, 41, 11, 34]])

In [18]:
top_indices = np.unravel_index(np.argpartition(matrix_x, -5, axis=None)[-5:], matrix_x.shape)

# Display the indices of the top 5 maximum values
print("\nIndices of the top 5 maximum values:")
for i, index in enumerate(top_indices):
    print(f"Top {i}: {index} -> Value: {matrix_x[index]}")


Indices of the top 5 maximum values:
Top 0: [1 5 0 4 6] -> Value: [[47 79 47 66 18 41 95 61 61 11]
 [96 48 38 34 70 78 58 48 46 47]
 [94 69 14  6 92 24 70 97 82 63]
 [ 8 26 14 14 36 51 89 99 21 50]
 [73 73 33 66 99 78 87 46 23 45]]
Top 1: [6 0 7 7 4] -> Value: [[73 73 33 66 99 78 87 46 23 45]
 [94 69 14  6 92 24 70 97 82 63]
 [67  3 77 89 74 82 87  5 84 46]
 [67  3 77 89 74 82 87  5 84 46]
 [ 8 26 14 14 36 51 89 99 21 50]]
