# Numpy

## sep 13

In [5]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
list = [1,2,34,54]
print(type(list))

<class 'list'>


### Access 2D Array Elements


In [9]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr1[0,2])

3


### Access 3D Array Elements

In [10]:
arr2 = np.array([[[1,2,3],[2,3,4]],[[5,6,7],[8,9,0]]])
print(arr2)


[[[1 2 3]
  [2 3 4]]

 [[5 6 7]
  [8 9 0]]]


In [11]:
print(arr2[1,0,2])

7


### Negative Indexing


In [12]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr1[1,-1])

0


### NumPy Array Slicing


In [13]:
arr = np.array([1,2,3,4,5])
print(arr[1:4])

[2 3 4]


### NumPy Array Slicing with step

In [15]:
print(arr[1:5:2])

[2 4]


### NumPy 2D Array Slicing with Step


In [16]:
print(arr1[1,1:4])

[7 8 9]


### Copy Numpy Array


In [17]:
ar = np.array([1,2,3,4,5])
x = ar.copy()
ar[0] = 98
print(ar)
print(x)

[98  2  3  4  5]
[1 2 3 4 5]


### Reshape Numpy Array


In [21]:
ar = np.array([1,2,3,4,5,6,7,8,9,10])
new_arr = ar.reshape(2,5)
print(new_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
